name: Build and Push to JFrog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 - Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3 - Compile the code
      - name: Compile
        run: mvn compile

      # Step 4 - Run tests
      - name: Run tests
        run: mvn test

      # Step 5 - Package application
      - name: Package JAR
        run: mvn clean package -DskipTests=false

      # Step 6 - Log in to JFrog Artifactory Docker registry
      - name: Docker login to JFrog
        run: echo "${{ secrets.JFROG_PASSWORD }}" | docker login ${{ secrets.JFROG_REGISTRY }} -u "${{ secrets.JFROG_USERNAME }}" --password-stdin

      # Step 7 - Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.JFROG_REGISTRY }}/${{ secrets.JFROG_REPO }}/spring-petclinic:latest .

      # Step 8 - Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.JFROG_REGISTRY }}/${{ secrets.JFROG_REPO }}/spring-petclinic:latest
